### ISSUE TITLE
Bokeh 0.12.10 causes parallel jobs to fail

### ISSUE THREAD

**Issue by chuaxr** [spencerahill/aospy#228]
After upgrading Bokeh from 0.12.5 to 0.12.10, using parallelize= True throws some errors, and then does not appear to do anything. This occurs even though Bokeh is not used in my code.  Reverting back to the previous version removed the issue. I highly doubt 0.12.5 versus 0.12.10 would make a difference for my use cases, but I would like to understand why installing a library that isn't used in my code might affect the functioning of the parallelizations.

I'm using tornado 4.5.1.

The error trace (which I interrupted after some time) follows:
```
python aospy_main.py
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
Traceback (most recent call last):
  File "aospy_main.py", line 167, in <module>
    calcs = submit_mult_calcs(calc_suite_specs, calc_exec_options)
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/aospy/automate.py", line 460, in submit_mult_calcs
    return _exec_calcs(calcs, **exec_options)
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/aospy/automate.py", line 304, in _exec_calcs
    with distributed.LocalCluster(n_workers=n_workers) as cluster:
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 117, in __init__
    sync(self.loop, self._start, ip)
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/utils.py", line 241, in sync
    six.reraise(*error[0])
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/utils.py", line 229, in f
    result[0] = yield make_coro()
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 149, in _start
    services=self.worker_services, **self.worker_kwargs)
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 155, in _start_all_workers
    yield [self._start_worker(**kwargs) for i in range(n_workers)]
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 828, in callback
    result_list.append(f.result())
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/site-packages/distributed/deploy/local.py", line 183, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.gen.TimeoutError: Worker failed to start
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/multiprocessing/forkserver.py", line 164, in main
    rfds = [key.fileobj for (key, events) in selector.select()]
  File "/nbhome/xrc/anaconda2/envs/py361/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
```

**Comment by spencerkclark** [comment]
Hmm...this is somewhat surprising, since our test suite on Travis seems to be passing using `bokeh` v0.12.10.  One difference is that it's using the latest version of `tornado` as well (v4.5.2).

See: https://travis-ci.org/spencerahill/aospy/jobs/298879124#L653
and https://travis-ci.org/spencerahill/aospy/jobs/298879124#L629

The explanation for why bokeh matters is that when using `parallelize=True`, `aospy` launches a [`distributed.LocalCluster`](http://distributed.readthedocs.io/en/latest/local-cluster.html?highlight=LocalCluster) to manage the computations.  The `LocalCluster` launches a bokeh server to show a [diagnostics page](http://distributed.readthedocs.io/en/latest/web.html) that allows you to track the progress of your computations.

Could you try upgrading `distributed` and `tornado` to their latest versions, and try again with the latest version of `bokeh`?

```
$ conda upgrade -c conda-forge distributed tornado bokeh
```

**Comment by chuaxr** [comment]
Yup, that worked. Is it possible to view the progress of aospy calculations on http://scheduler-address:8787 and/or the performance statistics after the run has completed?

**Comment by spencerkclark** [comment]
> Yup, that worked.

Great, thanks for trying that out!

> Is it possible to view the progress of aospy calculations on http://scheduler-address:8787 and/or the performance statistics after the run has completed?

After things have been completed, unfortunately no, because the bokeh server will have been shut down.  It's there mainly for real-time progress (for series of calculations that take longer than a minute or so).  To view it you'll need to make sure your port-forwarding setup enables it (I can help offline if you're interested).

**Comment by spencerahill** [comment]
Thanks @chuaxr for the report and @spencerkclark for troubleshooting.

Are we content with this Issue serving as the documentation about this potential problem involving the bokeh and tornado versions?  Or should we do something more formal?  I'm fine with the former, but that's pretty much entirely out of laziness.

**Comment by spencerkclark** [comment]
> Are we content with this Issue serving as the documentation about this potential problem involving the bokeh and tornado versions?

Yes, I'm totally fine with this approach.  It's hard to tell from what's going on in the stack trace, but given that simply updating the libraries solved things I suspect the incompatibility of the different versions stems from something upstream (i.e. it's not something we should concern ourselves with formally in `aospy`).

**Comment by spencerahill** [comment]
Sounds good to me! 😄
